sudo: true
dist: bionic
language: python

python:
  - 2.7
  - 3.6
  - 3.7

install:
  - ./travis_install.sh
  - pip install -r test-requirements.txt
  - pip install tox codecov

script:
  - tox -e py

after_success:
  - nosetests && codecov